# 训练配置
training:
  batch_size: 8
  learning_rate: 0.001
  epochs: 200
  weight_decay: 0.0001
  
# 模型配置
model:
  in_channels: 3
  num_classes: 1
  base_channels: 64
  prototype_dim: 256
  temperature_alpha: 2.0
  
# 损失权重
loss_weights:
  mask_loss: 1.0
  fg_loss: 0.5
  bg_loss: 0.5
  uncertainty_loss: 0.3
  
# 数据配置
data:
  image_size: [512, 512]
  train_split: 0.8
  val_split: 0.2
  
# 优化器配置
optimizer:
  type: "Adam"
  momentum: 0.9
  scheduler: "cosine"
